//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.19 at 04:44:24 AM CST 
//


package com.svgn.xero.domain.extended;

import java.util.HashMap;
import java.util.Map;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import com.svgn.xero.domain.Account;
import com.svgn.xero.domain.Address;
import com.svgn.xero.domain.ApiException;
import com.svgn.xero.domain.ApiExceptionExtended;
import com.svgn.xero.domain.ArrayOfAccount;
import com.svgn.xero.domain.ArrayOfAddress;
import com.svgn.xero.domain.ArrayOfAttachment;
import com.svgn.xero.domain.ArrayOfBankTransaction;
import com.svgn.xero.domain.ArrayOfBrandingTheme;
import com.svgn.xero.domain.ArrayOfContact;
import com.svgn.xero.domain.ArrayOfContactGroup;
import com.svgn.xero.domain.ArrayOfCreditNote;
import com.svgn.xero.domain.ArrayOfCurrency;
import com.svgn.xero.domain.ArrayOfEmployee;
import com.svgn.xero.domain.ArrayOfExpenseClaim;
import com.svgn.xero.domain.ArrayOfInvoice;
import com.svgn.xero.domain.ArrayOfItem;
import com.svgn.xero.domain.ArrayOfJournal;
import com.svgn.xero.domain.ArrayOfJournalLine;
import com.svgn.xero.domain.ArrayOfLineItem;
import com.svgn.xero.domain.ArrayOfManualJournal;
import com.svgn.xero.domain.ArrayOfManualJournalLine;
import com.svgn.xero.domain.ArrayOfOrganisation;
import com.svgn.xero.domain.ArrayOfPayment;
import com.svgn.xero.domain.ArrayOfPhone;
import com.svgn.xero.domain.ArrayOfReceipt;
import com.svgn.xero.domain.ArrayOfReport;
import com.svgn.xero.domain.ArrayOfTaxRate;
import com.svgn.xero.domain.ArrayOfTrackingCategory;
import com.svgn.xero.domain.ArrayOfTrackingCategoryOption;
import com.svgn.xero.domain.ArrayOfUser;
import com.svgn.xero.domain.ArrayOfValidationError;
import com.svgn.xero.domain.ArrayOfWarning;
import com.svgn.xero.domain.Attachment;
import com.svgn.xero.domain.BankTransaction;
import com.svgn.xero.domain.BrandingTheme;
import com.svgn.xero.domain.Contact;
import com.svgn.xero.domain.ContactGroup;
import com.svgn.xero.domain.ConversionDetails;
import com.svgn.xero.domain.CreditNote;
import com.svgn.xero.domain.Currency;
import com.svgn.xero.domain.Employee;
import com.svgn.xero.domain.ExpenseClaim;
import com.svgn.xero.domain.Hyperlink;
import com.svgn.xero.domain.Invoice;
import com.svgn.xero.domain.Item;
import com.svgn.xero.domain.ItemPriceDetails;
import com.svgn.xero.domain.Journal;
import com.svgn.xero.domain.JournalLine;
import com.svgn.xero.domain.LineItem;
import com.svgn.xero.domain.ManualJournal;
import com.svgn.xero.domain.ManualJournalLine;
import com.svgn.xero.domain.ObjectFactory;
import com.svgn.xero.domain.Organisation;
import com.svgn.xero.domain.Payment;
import com.svgn.xero.domain.Phone;
import com.svgn.xero.domain.Receipt;
import com.svgn.xero.domain.Report;
import com.svgn.xero.domain.ReportAttribute;
import com.svgn.xero.domain.ReportAttributes;
import com.svgn.xero.domain.ReportCell;
import com.svgn.xero.domain.ReportCellAttribute;
import com.svgn.xero.domain.ReportCellAttributes;
import com.svgn.xero.domain.ReportCells;
import com.svgn.xero.domain.ReportField;
import com.svgn.xero.domain.ReportFields;
import com.svgn.xero.domain.ReportRow;
import com.svgn.xero.domain.ReportRows;
import com.svgn.xero.domain.ReportTitles;
import com.svgn.xero.domain.ResponseType;
import com.svgn.xero.domain.SetupType;
import com.svgn.xero.domain.TaxRate;
import com.svgn.xero.domain.TrackingCategory;
import com.svgn.xero.domain.TrackingCategoryOption;
import com.svgn.xero.domain.User;
import com.svgn.xero.domain.ValidationError;
import com.svgn.xero.domain.Warning;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.svgn.xero.domain package. 
 * <p>An XeroObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class XeroObjectFactory extends ObjectFactory{

   
    private static Map qNameMap = new HashMap();
    static{
    	qNameMap.put(ArrayOfInvoice.class, _Invoices_QNAME);
    	qNameMap.put(ArrayOfPayment.class, _Payments_QNAME);
    	qNameMap.put(ArrayOfUser.class, _Users_QNAME);
    	qNameMap.put(ArrayOfOrganisation.class, _Organisations_QNAME);
    	qNameMap.put(ArrayOfItem.class, _Items_QNAME);
    	qNameMap.put(ArrayOfContact.class, _Contacts_QNAME);
    	qNameMap.put(ArrayOfAccount.class, _Accounts_QNAME);
    	
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfAccount }{@code >}}
     * @param <T>
     * 
     */
    
    public <T> JAXBElement<T> createObjects(T value) {
        return new JAXBElement((QName) qNameMap.get(value.getClass()), value.getClass(), null, value);
    }

}
